### ISSUE TITLE
Developing site body & footer

### ISSUE THREAD

**Issue by Space113** [Space113/static_website#3]
@mBlacksmith  add a body and footer using simple html tegs (add css styles if you fish)

**Comment by ghost** [comment]
Work done 

![shinobi](https://user-images.githubusercontent.com/37442236/37866528-65da7ef2-2f94-11e8-9528-565f7b52a344.png)

**Comment by ghost** [comment]
@1fcd641e95155cc2c2325b59a30e00660010e3d1

**Comment by ghost** [comment]
1fcd641e95155cc2c2325b59a30e00660010e3d1
